// Auto-generated by ROA Design System — DO NOT EDIT
// Project: BabyCare 우리아이 성장기록 (babycare)
// Run `roa sync` to regenerate

import SwiftUI

enum DS {
    enum Generated {
        static let brandPrimary = Color(red: 1.000, green: 0.710, blue: 0.761)
        static let brandAccent = Color(red: 1.000, green: 0.710, blue: 0.761)

        // Spacing

        // Radius
        static let radius_sm: CGFloat = 3
        static let radius_md: CGFloat = 8
        static let radius_lg: CGFloat = 12
        static let radius_xl: CGFloat = 14
        static let radius_xxl: CGFloat = 16
        static let radius_3xl: CGFloat = 20
    }
}
